# Configuración global de TheGuard

# Rutas de los módulos
paths:
  ids_firmas: ./modules/ids_firmas
  analisis_anomalias: ./modules/analisis_anomalias
  dpi: ./modules/dpi
  monitorizacion_ip: ./modules/monitorizacion_ip
  dashboard: ./modules/dashboard

# Configuración de Snort
snort:
  config_path: ./config/snort/snort.conf
  rules_path: ./config/snort/local.rules
  alert_file: /var/log/snort/alert

# Configuración de Machine Learning
ml_config:
  model_path: ./modules/analisis_anomalias/model
  batch_size: 32
  epochs: 100
  validation_split: 0.2
  threshold: 0.8

# Configuración de red
network:
  interface: eth0
  capture_filter: "tcp or udp"
  max_packet_size: 65535

# Configuración del Dashboard
dashboard:
  host: localhost
  port: 5000
  debug: true
  secret_key: "your-secret-key-here"

# APIs externas
apis:
  abuseipdb:
    api_key: "your-api-key-here"
    base_url: "https://api.abuseipdb.com/api/v2"

# Logging
logging:
  level: INFO
  file: ./logs/theguard.log
  max_size: 10MB
  backup_count: 5