%YAML 1.1
---
# Suricata configuration file

# Network variable configuration
vars:
  address-groups:
    HOME_NET: "[192.168.0.0/16,10.0.0.0/8,172.16.0.0/12]"
    EXTERNAL_NET: "!$HOME_NET"
    HTTP_SERVERS: "$HOME_NET"
    SQL_SERVERS: "$HOME_NET"
    DNS_SERVERS: "$HOME_NET"
    SMTP_SERVERS: "$HOME_NET"
    TELNET_SERVERS: "$HOME_NET"
    AIM_SERVERS: "$EXTERNAL_NET"

# Stats configuration
stats:
  enabled: yes
  interval: 10
  decoder-events: true
  http-events: true
  dns-events: true
  tls-events: true

# Logging configuration
outputs:
  - eve-log:
      enabled: yes
      filetype: regular
      filename: /var/log/theguard/suricata/eve.json
      types:
        - alert
        - http
        - dns
        - tls
        - ssh
  - stats:
      enabled: yes
      filename: stats.log
      interval: 10

# Performance optimizations
max-pending-packets: 1024
detect-engine:
  - profile: medium
  - custom-values:
      toclient-src-groups: 2
      toclient-dst-groups: 2
      toclient-sp-groups: 2
      toclient-dp-groups: 3
      toserver-src-groups: 2
      toserver-dst-groups: 4
      toserver-sp-groups: 2
      toserver-dp-groups: 25
  - sgh-mpm-context: auto
  - inspection-recursion-limit: 3000

# Detection configuration
app-layer:
  protocols:
    tls:
      enabled: yes
    http:
      enabled: yes
    dns:
      enabled: yes
    ssh:
      enabled: yes
    dnp3:
      enabled: yes

# Rules and classifications
default-rule-path: /etc/suricata/rules
rule-files:
  - custom/*.rules
  - "*.rules"

classification-file: /etc/suricata/rules/classification.config
reference-config-file: /etc/suricata/rules/reference.config

# Logging configuration
logging:
  default-log-level: info
  outputs:
    - console:
        enabled: yes
    - file:
        enabled: yes
        filename: /var/log/theguard/suricata/suricata.log
        level: info

# Packet capture configuration
af-packet:
  - interface: eth0
    threads: auto
    cluster-id: 99
    cluster-type: cluster_flow
    defrag: yes
    use-mmap: yes
    tpacket-v3: yes